{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "volume-limiting-controller.serviceAccountName" . }}
  labels:
{{ include "volume-limiting-controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ include "volume-limiting-controller.fullname" .  }}
  labels:
{{ include "volume-limiting-controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ include "volume-limiting-controller.fullname" .  }}
  labels:
{{ include "volume-limiting-controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "volume-limiting-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Release.Namespace }}-{{ include "volume-limiting-controller.fullname" .  }}
{{- end -}}
